spring:
  application:
    name: mobile-management-platform

  datasource:
    url: jdbc:postgresql://localhost:5432/mmp
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop    # crea/actualiza tablas según @Entity (no borra datos)
    show-sql: true         # muestra SQL por consola
    open-in-view: false
    properties:
      hibernate:
        format_sql: true   # formatea el SQL en varias líneas

logging:
  level:
    org.hibernate.SQL: debug                 # sentencia SQL
    org.hibernate.orm.jdbc.bind: trace       # parámetros (values) de las queries

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui
  info:
    title: Digital Citizen - Client Service API
    description: REST API documentation for client management
    version: 1.0.0



